N_TASKS: 10
N_CLASSES_PER_TASK: 10
N_CLASSES: 100
SIZE: [224, 224]
MEAN: [0, 0, 0]
STD: [1, 1, 1]
TRANSFORM:
  - RandomResizedCrop:
      size: 224
  - RandomHorizontalFlip
  - ToTensor
  - Normalize:
      mean: [0, 0, 0]
      std: [1, 1, 1]
TEST_TRANSFORM:
  - Resize:
      size: 224
  - ToTensor
  - Normalize:
      mean: [0, 0, 0]
      std: [1, 1, 1]
batch_size: 128
n_epochs: 20
